apiVersion: v1
kind: Pod
metadata:
  name: naginx
  namespace: roboshop
  labels:
    name: naginx
    project: roboshop
spec:
  containers:
  - name: naginx
    image: naginx
    ports:
    - containerPort: 80